# Generated by Django 4.0.5 on 2022-06-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basiccv',
            name='cv_number',
            field=models.CharField(default=12345, max_length=20),
            preserve_default=False,
        ),
    ]
