# Generated by Django 4.0.5 on 2022-06-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_remove_basiccv_cv_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basiccv',
            old_name='user',
            new_name='owner',
        ),
    ]
