# Generated by Django 4.0.5 on 2022-06-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_rename_user_basiccv_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='basiccv',
            name='cv_code',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
