# Generated by Django 4.0.5 on 2022-06-28 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_remove_basiccv_cv_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='basiccv',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basiccv',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
